
services:
  
  webql:
    image: webql:1.0.0
    container_name: webql
    restart: always
    build:
      context: ./webql
      dockerfile: Dockerfile
    networks:
      - graphqlastic-net
    ports:
      - 5173:5173
    expose:
      - 5173
    # depends_on:
    #   - server
    volumes:
      - ./webql:/webql
      - /webql/node_modules
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
  
  server:
    image: server:1.0.0
    container_name: server
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5050:5050
    env_file:
      - .env
    networks:
      - graphqlastic-net
    volumes:
      - ./server:/server
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - graphqlastic-net
    
    

networks:
  graphqlastic-net:
    driver: bridge

volumes:
  nodemodules: {}
  esdata: 
    driver: local