// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewEntity struct {
	Name     string  `json:"name"`
	CageCode *string `json:"cageCode,omitempty"`
}

type Query struct {
}
