FROM golang:1.22.4 as builder

# Set destination for COPY
WORKDIR /app

COPY ./ /app/server

# Navigate to the server directory
WORKDIR /app/server

# Build the Go app
RUN go build -o server server.go

# Expose port 5050 to the outside world
EXPOSE 5050

# Command to run the executable
CMD ["./server"]
